### ISSUE TITLE
eopatch.save(folder) Error

### ISSUE THREAD

**Issue by mustafateke** [sentinel-hub/cv4a-iclr-2020-starter-notebooks#3]
I got this error for folder: eopatch-00-0-0
OS Windows 10 x64 Anaconda
Exception has occurred: ValueError
Cannot save features {(<FeatureType.TIMESTAMP: 'timestamp'>, Ellipsis), (<FeatureType.DATA: 'data'>, 's2-bands-l2a'), (<FeatureType.DATA: 'data'>, 'cloud_prob'), (<FeatureType.MASK_TIMELESS: 'mask_timeless'>, 'crop_id'), (<FeatureType.MASK_TIMELESS: 'mask_timeless'>, 'field_id')} with overwrite_permission=OverwritePermission.ADD_ONLY 
  File "E:\Agriculture\cv4a\cv4a-crop-challenge-to-eolearn.py", line 152, in save_as_eopatch
    eopatch.save(folder)
  File "E:\Agriculture\cv4a\cv4a-crop-challenge-to-eolearn.py", line 178, in <module>
    save_as_eopatch(data, label, field, dates, eop_folder)
  File "<string>", line 1, in <module>

**Comment by devisperessutti** [comment]
Probably patches are already existing, and write permission should be changed. 

This change should fix it `eopatch.save(folder, overwrite_permission=OverwritePermission.OVERWRITE_PATCH)`

**Comment by mustafateke** [comment]
Thanks. Actually the files were written. It may be that the files already existed.
