### ISSUE TITLE
from eolearn.features 

### ISSUE THREAD

**Issue by mustafateke** [sentinel-hub/cv4a-iclr-2020-starter-notebooks#4]
I got this error, I installed files via pip
from eolearn.features import SimpleFilterTask, LinearInterpolation, ValueFilloutTask, NormalizedDifferenceIndexTask

Exception has occurred: ImportError
cannot import name '_validate_lengths'
  File "E:\Agriculture\cv4a\cv4a-process-and-train.py", line 35, in <module>
    from eolearn.features import SimpleFilterTask, LinearInterpolation, ValueFilloutTask, NormalizedDifferenceIndexTask
  File "<string>", line 1, in <module>

**Comment by devisperessutti** [comment]
try upgrade `scikit-image` first, and if error persists,  `numpy`
