### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by daisy12321** [sentinel-hub/cv4a-iclr-2020-starter-notebooks#5]
I am hoping to replicate the experiment from https://github.com/sentinel-hub/cv4a-iclr-2020-starter-notebooks/blob/master/experiments/intercropping.ipynb

Specifically, it references some prepared data from MLHub:
`NP_DATA_PATH = '/mnt/azrael/spatialdata/projects/eo_data/iclr-2020-challange/mlhub/prepared_data/original_data.npz'`

I can download the raw data from the challenge on the MLHub website, but can't find the prepared ones, or the script that was used to generate them. Could you point me to them if they are available?

**Comment by batic** [comment]
Hi @daisy12321 ,

We don't have the data any longer, but with some luck you should be able to recreate it.

If I am not mistaken (that code has been prepared and used quite some time ago), the numpy arrays you are after were prepared in the https://github.com/sentinel-hub/cv4a-iclr-2020-starter-notebooks/blob/338cdcfa8c342600ef0d2bd4e10c7aa04c6bdd14/cv4a-process-and-train.ipynb. If you see cell 20, it creates `features`, `field_id` and `crop_id`. 

Hope that helps.

**Comment by daisy12321** [comment]
Thank you so much for the prompt answer!
